from app.models.skill import Skill


def build_readme(persona_data: dict, skills: list[Skill]) -> str:
    name = persona_data.get("name") or "Unnamed Persona"
    category = persona_data.get("category", "")
    description_summary = persona_data.get("description_summary", "")

    if skills:
        skills_section = "\n".join(f"- **{skill.name}** — {skill.description}" for skill in skills)
    else:
        skills_section = "_No skills attached._"

    return (
        f"# {name}\n"
        "\n"
        f"> {description_summary}\n"
        "\n"
        f"**Category:** {category}\n"
        "\n"
        "## Persona Files\n"
        "- [Identity](./identity.md)\n"
        "- [Soul](./soul.md)\n"
        "- [DNA](./dna.md)\n"
        "- [Overview](./overview.md)\n"
        "- [Heartbeat](./heartbeat.md)\n"
        "\n"
        "## Skills\n"
        f"{skills_section}\n"
        "\n"
        "---\n"
        "_Generated by Anvila_\n"
    )
