from app.models.skill import Skill


def build_readme(persona_data: dict, skills: list[Skill]) -> str:
    # persona_data keys used:
    #   "name"                : str  — persona display name
    #   "category"            : str  — category string
    #   "description_summary" : str  — one-line description
    #
    # skills: list of Skill ORM objects
    #   Use skill.name and skill.description per entry.
    #
    # Output template (build this string):
    #
    #   # {name}
    #
    #   > {description_summary}
    #
    #   **Category:** {category}
    #
    #   ## Persona Files
    #   - [Identity](./identity.md)
    #   - [Soul](./soul.md)
    #   - [DNA](./dna.md)
    #   - [Overview](./overview.md)
    #   - [Heartbeat](./heartbeat.md)
    #
    #   ## Skills
    #   - **{skill.name}** — {skill.description}
    #   (one line per skill)
    #
    #   ---
    #   _Generated by Anvila_
    #
    # Returns the complete README markdown string.
    raise NotImplementedError
