from app.core.config import settings
from app.models.skill import Skill


def build_readme(persona_data: dict, skills: list[Skill]) -> str:
    name = persona_data.get("name") or "Unnamed Persona"
    category = persona_data.get("category", "")
    description_summary = persona_data.get("description_summary", "")

    if skills:
        skill_entries = []
        for i, skill in enumerate(skills, start=6):
            folder = skill.slug.split("/")[-1]
            tags = ", ".join(skill.tags) if skill.tags else "general"
            entry = (
                f"### {i}. [{skill.name}](./skills/{folder}/SKILL.md)\n"
                f"**Tags:** {tags}\n"
                f"> {skill.description}\n\n"
                f"Read `./skills/{folder}/SKILL.md` for installation and activation instructions."
            )
            skill_entries.append(entry)
        skills_section = "\n\n".join(skill_entries)
    else:
        skills_section = "_No skills attached._"

    return (
        f"# {name}\n"
        "\n"
        f"> {description_summary}\n"
        "\n"
        f"**Category:** {category}\n"
        "\n"
        "---\n"
        "\n"
        "## How to load this persona\n"
        "\n"
        "You are an AI agent. This repository is your persona. "
        "Read the files below in order — each one builds on the last. "
        "Do not skip any file. After loading all files, you will know who you are, "
        "how you think, and what you can do.\n"
        "\n"
        "---\n"
        "\n"
        "## Persona files\n"
        "\n"
        "### 1. [identity.md](./identity.md) — Who you are\n"
        "Your name, role, and the core purpose you exist to serve. "
        "This defines how you introduce yourself and the lens through which you see every task.\n"
        "\n"
        "### 2. [soul.md](./soul.md) — Why you exist\n"
        "Your values, motivations, and what you care about deeply. "
        "When facing ambiguity, return to this file — it tells you what matters.\n"
        "\n"
        "### 3. [dna.md](./dna.md) — How you think\n"
        "Your reasoning style, decision-making patterns, and cognitive tendencies. "
        "This shapes how you approach problems, not just what conclusions you reach.\n"
        "\n"
        "### 4. [overview.md](./overview.md) — What you do\n"
        "Your capabilities, areas of expertise, and the kinds of tasks you handle well. "
        "Use this to understand your own scope and communicate it to others.\n"
        "\n"
        "### 5. [heartbeat.md](./heartbeat.md) — How you behave\n"
        "Your communication style, tone, habits, and rituals. "
        "This is the moment-to-moment texture of how you show up in every interaction.\n"
        "\n"
        "---\n"
        "\n"
        "## Skills\n"
        "\n"
        "Skills are discrete capabilities you can invoke. "
        "Each skill folder contains a SKILL.md with instructions on how to install "
        "and activate that skill. Read the SKILL.md before attempting to use the skill.\n"
        "\n"
        f"{skills_section}\n"
        "\n"
        "---\n"
        "\n"
        f"_Generated by [Anvila](https://github.com/{settings.GITHUB_ORG})_\n"
    )
