"""add chat fields and file fields to persona

Revision ID: 087b4ba9b403
Revises: c2e41d7a346c
Create Date: 2026-05-18 14:51:55.006726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087b4ba9b403'
down_revision: Union[str, None] = 'c2e41d7a346c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('identity_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('soul_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('dna_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('overview_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('heartbeat_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('readme_md', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('job_id', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('error_code', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('personas', sa.Column('is_listed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('personas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'deleted_at')
    op.drop_column('personas', 'is_listed')
    op.drop_column('personas', 'tokens_used')
    op.drop_column('personas', 'error_code')
    op.drop_column('personas', 'job_id')
    op.drop_column('personas', 'readme_md')
    op.drop_column('personas', 'heartbeat_md')
    op.drop_column('personas', 'overview_md')
    op.drop_column('personas', 'dna_md')
    op.drop_column('personas', 'soul_md')
    op.drop_column('personas', 'identity_md')
    # ### end Alembic commands ###
