"""update slug to unique

Revision ID: 2d37d86295d1
Revises: a5998cab4ca6
Create Date: 2026-05-19 10:47:25.127490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d37d86295d1"
down_revision: Union[str, None] = "a5998cab4ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    bind.execute(
        sa.text("""
        WITH duplicate_slugs AS (
            SELECT
                id,
                slug,
                ROW_NUMBER() OVER (
                    PARTITION BY slug
                    ORDER BY created_at ASC, id ASC
                ) AS row_number
            FROM skills
            WHERE slug IS NOT NULL
        )
        UPDATE skills
        SET slug = LEFT(skills.slug, 210) || '-' || SUBSTRING(skills.id::text, 1, 8)
        FROM duplicate_slugs
        WHERE skills.id = duplicate_slugs.id
        AND duplicate_slugs.row_number > 1
        """)
    )

    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    # ### end Alembic commands ###
