"""fix migrations

Revision ID: 524a6fac3e5b
Revises: c0ef718a8c35
Create Date: 2026-05-19 11:13:49.789093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524a6fac3e5b'
down_revision: Union[str, None] = 'c0ef718a8c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
