"""chat session is one to one to persona

Revision ID: a485bb87cba5
Revises: a5998cab4ca6
Create Date: 2026-05-19 10:35:14.175781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a485bb87cba5'
down_revision: Union[str, None] = 'a5998cab4ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
