"""add_token_version_to_user

Revision ID: ad889766bdf1
Revises: 5863da6e5ee1
Create Date: 2026-06-03 08:40:04.518370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad889766bdf1"
down_revision: Union[str, None] = "5863da6e5ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("token_version", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    # ### end Alembic commands ###
