"""'add_generation_fields

Revision ID: c2e41d7a346c
Revises: e1f2a3b4c5d6
Create Date: 2026-05-18 14:34:41.742447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e41d7a346c'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_connected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('generation_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('refine_used', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refine_used')
    op.drop_column('users', 'total_tokens_used')
    op.drop_column('users', 'generation_count')
    op.drop_column('users', 'github_connected')
    op.drop_column('users', 'github_access_token_encrypted')
    # ### end Alembic commands ###
