from dataclasses import dataclass

from app.services.readme_builder import build_readme


@dataclass
class _SkillStub:
    """Stand-in for app.models.skill.Skill that exposes only the attributes
    build_readme reads. Keeps tests free of the ORM session/registry."""

    name: str
    description: str


def test_golden_output_with_two_skills() -> None:
    persona_data = {
        "name": "Lighthouse",
        "category": "support",
        "description_summary": "Tier-1 SaaS support agent for SMB customers.",
    }
    skills = [
        _SkillStub(name="ticket_triage", description="Classify and route inbound tickets."),
        _SkillStub(name="empathy_writer", description="Draft warm, concise replies."),
    ]

    expected = (
        "# Lighthouse\n"
        "\n"
        "> Tier-1 SaaS support agent for SMB customers.\n"
        "\n"
        "**Category:** support\n"
        "\n"
        "## Persona Files\n"
        "- [Identity](./identity.md)\n"
        "- [Soul](./soul.md)\n"
        "- [DNA](./dna.md)\n"
        "- [Overview](./overview.md)\n"
        "- [Heartbeat](./heartbeat.md)\n"
        "\n"
        "## Skills\n"
        "- **ticket_triage** — Classify and route inbound tickets.\n"
        "- **empathy_writer** — Draft warm, concise replies.\n"
        "\n"
        "---\n"
        "_Generated by Anvila_\n"
    )

    assert build_readme(persona_data, skills) == expected


def test_all_six_section_headings_are_present() -> None:
    output = build_readme(
        {"name": "X", "category": "sales", "description_summary": "y"},
        [],
    )
    assert "# X" in output
    assert "**Category:** sales" in output
    assert "## Persona Files" in output
    assert "- [Identity](./identity.md)" in output
    assert "- [Soul](./soul.md)" in output
    assert "- [DNA](./dna.md)" in output
    assert "- [Overview](./overview.md)" in output
    assert "- [Heartbeat](./heartbeat.md)" in output
    assert "## Skills" in output


def test_empty_skills_list_emits_placeholder_line() -> None:
    output = build_readme(
        {"name": "X", "category": "sales", "description_summary": "y"},
        [],
    )
    assert "_No skills attached._" in output
    assert "- **" not in output


def test_missing_name_falls_back_to_unnamed_persona() -> None:
    output = build_readme(
        {"category": "sales", "description_summary": "y"},
        [],
    )
    assert output.startswith("# Unnamed Persona\n")
