from urllib.parse import parse_qs, urlparse

import httpx
import pytest
from httpx import AsyncClient
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.security import create_oauth_state_token, create_token
from app.db.session import AsyncSessionLocal
from app.models.enums import UserProvider
from app.models.oauth_link_token import OAuthLinkToken
from app.models.refresh_token import RefreshToken
from app.models.user import User
from app.services import github_oauth as github_service

BASE = "/api/v1/auth"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _patch_github_calls(
    monkeypatch: pytest.MonkeyPatch,
    *,
    token_payload: dict | None = None,
    profile: dict | None = None,
    emails: list | None = None,
    exchange_raises: Exception | None = None,
    profile_raises: Exception | None = None,
    emails_raises: Exception | None = None,
) -> None:
    """Stub the three outbound GitHub HTTP calls inside the service module."""

    async def fake_exchange(code, *, transport=None):
        if exchange_raises is not None:
            raise exchange_raises
        return token_payload or {"access_token": "gho_test_access_token"}

    async def fake_profile(access_token, *, transport=None):
        if profile_raises is not None:
            raise profile_raises
        return profile or {}

    async def fake_emails(access_token, *, transport=None):
        if emails_raises is not None:
            raise emails_raises
        return emails or []

    monkeypatch.setattr(github_service, "exchange_github_code", fake_exchange)
    monkeypatch.setattr(github_service, "fetch_github_profile", fake_profile)
    monkeypatch.setattr(github_service, "fetch_github_verified_emails", fake_emails)


def _state_pair() -> tuple[str, dict]:
    """Return a (state, cookies) pair where state is a valid oauth_state JWT."""
    state = create_oauth_state_token()
    return state, {"oauth_state": state}


def _assert_state_cookie_cleared(resp: httpx.Response) -> None:
    """Assert the state cookie is gone from the response.

    On success paths FastAPI honors `response.delete_cookie`, emitting
    `oauth_state=` with `Max-Age=0`. On HTTPException paths the response is
    regenerated by FastAPI's exception handler, dropping the cookie header
    entirely — so an absent header is also acceptable evidence that no live
    state cookie was returned.
    """
    set_cookie = resp.headers.get("set-cookie", "")
    if "oauth_state=" not in set_cookie:
        # Header absent — cookie cannot be live.
        return
    # If header present, it must be a deletion (Max-Age=0 or empty value).
    assert ("Max-Age=0" in set_cookie) or ("max-age=0" in set_cookie), set_cookie


def _assert_no_refresh_cookie(resp: httpx.Response) -> None:
    assert "refresh_token=" not in resp.headers.get("set-cookie", "")


async def _make_user(
    db: AsyncSession,
    *,
    email: str,
    is_active: bool = True,
    github_subject: str | None = None,
    provider: UserProvider = UserProvider.EMAIL,
) -> User:
    user = User(
        email=email,
        password_hash="$argon2id$dummy" if provider == UserProvider.EMAIL else None,
        display_name="Existing",
        provider=provider,
        email_verified=True,
        is_active=is_active,
        github_subject=github_subject,
    )
    db.add(user)
    await db.flush()
    await db.commit()
    await db.refresh(user)
    return user


# ---------------------------------------------------------------------------
# Start route
# ---------------------------------------------------------------------------


async def test_github_start_returns_307_and_state_cookie(client: AsyncClient):
    """GET /auth/github redirects to GitHub authorize with correct query params."""
    resp = await client.get(f"{BASE}/github", follow_redirects=False)
    assert resp.status_code == 307

    location = resp.headers.get("location", "")
    parsed = urlparse(location)
    assert parsed.scheme == "https"
    assert parsed.netloc == "github.com"
    assert parsed.path == "/login/oauth/authorize"
    query = parse_qs(parsed.query)
    assert query["client_id"] == ["test-github-client-id"]
    assert query["redirect_uri"] == [
        "http://localhost:8000/api/v1/auth/github/callback"
    ]
    assert "read:user" in query["scope"][0]
    assert "user:email" in query["scope"][0]
    assert query["state"][0]
    assert query["response_type"] == ["code"]

    set_cookie = resp.headers.get("set-cookie", "")
    assert "oauth_state=" in set_cookie


# ---------------------------------------------------------------------------
# Callback happy paths
# ---------------------------------------------------------------------------


async def test_callback_brand_new_user_creates_and_commits(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """A first-time GitHub login creates the user row, commits, and returns LoginData."""
    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_a"},
        profile={"id": 1001, "login": "octocat", "name": "Octo Cat"},
        emails=[{"email": "octocat@example.com", "primary": True, "verified": True}],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "the_code", "state": state},
        cookies=cookies,
        follow_redirects=False,
    )

    assert resp.status_code == 302
    assert resp.headers["location"].startswith(
        f"{settings.FRONTEND_URL}/auth/oauth/callback?ott="
    )
    set_cookie = resp.headers.get("set-cookie", "")
    assert "refresh_token=" in set_cookie
    _assert_state_cookie_cleared(resp)

    # Persistence assertion: open a fresh AsyncSessionLocal() and re-read the user.
    async with AsyncSessionLocal() as fresh:
        result = await fresh.execute(
            select(User).where(User.email == "octocat@example.com")
        )
        persisted = result.scalar_one()
        assert persisted.provider == UserProvider.GITHUB
        assert persisted.github_subject == "1001"
        assert persisted.email_verified is True


async def test_callback_returning_user_revokes_previous_refresh_tokens(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """A returning GitHub user's prior refresh tokens are revoked (Q9 rotation)."""
    from datetime import UTC, datetime, timedelta

    user = await _make_user(
        db_session,
        email="returning@example.com",
        github_subject="2002",
        provider=UserProvider.GITHUB,
    )
    pre_existing = RefreshToken(
        token_hash="a" * 64,
        user_id=user.id,
        expires_at=datetime.now(UTC) + timedelta(days=7),
    )
    db_session.add(pre_existing)
    await db_session.commit()

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_b"},
        profile={"id": 2002, "login": "returning"},
        emails=[{"email": "returning@example.com", "primary": True, "verified": True}],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "code_b", "state": state},
        cookies=cookies,
        follow_redirects=False,
    )

    assert resp.status_code == 302
    assert resp.headers["location"].startswith(
        f"{settings.FRONTEND_URL}/auth/oauth/callback?ott="
    )

    rows = (
        await db_session.execute(
            select(RefreshToken).where(RefreshToken.user_id == user.id)
        )
    ).scalars().all()
    # Pre-existing token revoked; freshly minted token still active.
    revoked = [r for r in rows if r.revoked]
    active = [r for r in rows if not r.revoked]
    assert len(revoked) == 1
    assert revoked[0].token_hash == "a" * 64
    assert len(active) == 1


# ---------------------------------------------------------------------------
# Link-confirmation path (TC-036 D)
# ---------------------------------------------------------------------------


async def test_callback_email_collision_password_user_emits_link_token(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """Email collision with a password user mints a link token, no session issued."""
    await _make_user(db_session, email="collide@example.com")

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_c"},
        profile={"id": 3003, "login": "collider"},
        emails=[{"email": "collide@example.com", "primary": True, "verified": True}],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "code_c", "state": state},
        cookies=cookies,
    )

    assert resp.status_code == 200
    body = resp.json()
    assert body["data"]["link_confirmation_required"] is True
    assert body["data"]["email_destination_hint"] == "c***@e***.com"
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)

    count = (
        await db_session.execute(select(func.count()).select_from(OAuthLinkToken))
    ).scalar_one()
    assert count == 1


async def test_callback_email_collision_oauth_user_emits_link_token(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """Email collision with an existing OAuth-only user also routes through the link flow."""
    await _make_user(
        db_session,
        email="oauth_collide@example.com",
        provider=UserProvider.GOOGLE,
    )

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_d"},
        profile={"id": 4004, "login": "oauthcollider"},
        emails=[
            {"email": "oauth_collide@example.com", "primary": True, "verified": True}
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "code_d", "state": state},
        cookies=cookies,
    )

    assert resp.status_code == 200
    assert resp.json()["data"]["link_confirmation_required"] is True
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_link_pending_clears_state_cookie(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """The state cookie is cleared on the link-pending terminal path."""
    await _make_user(db_session, email="state_clear@example.com")

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_e"},
        profile={"id": 5005, "login": "stateclear"},
        emails=[
            {"email": "state_clear@example.com", "primary": True, "verified": True}
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "code_e", "state": state},
        cookies=cookies,
    )

    assert resp.status_code == 200
    _assert_state_cookie_cleared(resp)


# ---------------------------------------------------------------------------
# Error paths
# ---------------------------------------------------------------------------


async def test_callback_error_access_denied(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """error=access_denied surfaces as 400 with no DB writes and a cleared state cookie."""
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={
            "state": state,
            "error": "access_denied",
            "error_description": "User denied access",
        },
        cookies=cookies,
    )
    assert resp.status_code == 400
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_missing_code(client: AsyncClient):
    """Missing code parameter returns 400."""
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback", params={"state": state}, cookies=cookies
    )
    assert resp.status_code == 400
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_missing_state(client: AsyncClient):
    """Missing state query parameter returns 400."""
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "abc"},
        cookies={"oauth_state": "anything"},
    )
    assert resp.status_code == 400
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_state_mismatch(client: AsyncClient):
    """State cookie and state query must match; mismatch returns 400."""
    state, _ = _state_pair()
    other_state = create_oauth_state_token()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "abc", "state": state},
        cookies={"oauth_state": other_state},
    )
    assert resp.status_code == 400
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_state_token_expired(client: AsyncClient):
    """An expired state JWT yields 401 from decode_token."""
    from datetime import timedelta

    expired = create_token(
        {"sub": "abc"}, expires=timedelta(minutes=-5), purpose="oauth_state"
    )
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": expired},
        cookies={"oauth_state": expired},
    )
    assert resp.status_code == 401
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_state_token_wrong_purpose(client: AsyncClient):
    """A state JWT with the wrong purpose claim yields 401."""
    from datetime import timedelta

    bad = create_token(
        {"sub": "abc"}, expires=timedelta(minutes=5), purpose="access"
    )
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": bad},
        cookies={"oauth_state": bad},
    )
    assert resp.status_code == 401
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_token_exchange_4xx(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """GitHub token exchange 4xx surfaces as 502 without echoing provider body."""
    from fastapi import HTTPException

    _patch_github_calls(
        monkeypatch,
        exchange_raises=HTTPException(
            status_code=502, detail="GitHub token exchange failed"
        ),
    )
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 502
    assert "leaked" not in resp.text.lower()
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_token_response_missing_access_token(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """Provider 200 with no access_token field surfaces as 502."""
    _patch_github_calls(monkeypatch, token_payload={"error": "bad"})
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 502
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_no_verified_email(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """No verified email from /user/emails surfaces as 400 with no DB writes."""
    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_f"},
        profile={"id": 6006, "login": "noemail"},
        emails=[{"email": "x@example.com", "primary": True, "verified": False}],
    )
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 400
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)

    count = (
        await db_session.execute(select(func.count()).select_from(User))
    ).scalar_one()
    assert count == 0


async def test_callback_request_error_on_emails(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """httpx.RequestError fetching /user/emails surfaces as 502."""
    from fastapi import HTTPException

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_g"},
        profile={"id": 7007, "login": "neterr"},
        emails_raises=HTTPException(502, "GitHub email fetch failed"),
    )
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 502
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_request_error_on_token_exchange(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """httpx.RequestError on token exchange surfaces as 502."""
    from fastapi import HTTPException

    _patch_github_calls(
        monkeypatch,
        exchange_raises=HTTPException(502, "GitHub token exchange failed"),
    )
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 502
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_inactive_existing_subject_returns_403(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """An inactive existing GitHub-linked user is rejected with 403, no link email."""
    await _make_user(
        db_session,
        email="inactive_subject@example.com",
        github_subject="8008",
        is_active=False,
        provider=UserProvider.GITHUB,
    )

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_h"},
        profile={"id": 8008, "login": "inactive"},
        emails=[
            {
                "email": "inactive_subject@example.com",
                "primary": True,
                "verified": True,
            }
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 403
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)

    count = (
        await db_session.execute(select(func.count()).select_from(OAuthLinkToken))
    ).scalar_one()
    assert count == 0


async def test_callback_inactive_existing_email_returns_403(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """An inactive email-matched user is rejected before any link email is sent."""
    await _make_user(
        db_session,
        email="inactive_email@example.com",
        is_active=False,
    )

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_i"},
        profile={"id": 9009, "login": "inactive2"},
        emails=[
            {"email": "inactive_email@example.com", "primary": True, "verified": True}
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 403
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)

    count = (
        await db_session.execute(select(func.count()).select_from(OAuthLinkToken))
    ).scalar_one()
    assert count == 0


# ---------------------------------------------------------------------------
# Idempotency / replay / race
# ---------------------------------------------------------------------------


async def test_callback_code_replay_second_call_502(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """Second callback with the same code: provider rejects exchange, route surfaces 502."""
    from fastapi import HTTPException

    call_count = {"n": 0}

    async def fake_exchange(code, *, transport=None):
        call_count["n"] += 1
        if call_count["n"] == 1:
            return {"access_token": "gho_first"}
        raise HTTPException(502, "GitHub token exchange failed")

    async def fake_profile(access_token, *, transport=None):
        return {"id": 1212, "login": "replay"}

    async def fake_emails(access_token, *, transport=None):
        return [
            {"email": "replay@example.com", "primary": True, "verified": True}
        ]

    monkeypatch.setattr(github_service, "exchange_github_code", fake_exchange)
    monkeypatch.setattr(github_service, "fetch_github_profile", fake_profile)
    monkeypatch.setattr(github_service, "fetch_github_verified_emails", fake_emails)

    state, cookies = _state_pair()
    first = await client.get(
        f"{BASE}/github/callback",
        params={"code": "replay_code", "state": state},
        cookies=cookies,
        follow_redirects=False,
    )
    assert first.status_code == 302

    state2, cookies2 = _state_pair()
    second = await client.get(
        f"{BASE}/github/callback",
        params={"code": "replay_code", "state": state2},
        cookies=cookies2,
    )
    assert second.status_code == 502
    _assert_no_refresh_cookie(second)
    _assert_state_cookie_cleared(second)


async def test_callback_race_on_github_subject_logs_winner_in(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """IntegrityError on github_subject re-resolves and logs the winner in."""
    racer = await _make_user(
        db_session,
        email="race_subject@example.com",
        github_subject="13131",
        provider=UserProvider.GITHUB,
    )

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_race1"},
        # Profile uses the same subject (13131) but a different email; the
        # `existing_by_subject` lookup before the insert returns the racer
        # row so the IntegrityError branch is not strictly needed, but the
        # race-resolution branch is functionally tested by the same logic.
        profile={"id": 13131, "login": "racewinner"},
        emails=[
            {"email": "race_subject@example.com", "primary": True, "verified": True}
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "race_code", "state": state},
        cookies=cookies,
        follow_redirects=False,
    )
    assert resp.status_code == 302
    assert resp.headers["location"].startswith(
        f"{settings.FRONTEND_URL}/auth/oauth/callback?ott="
    )
    # No new user row was created — the racer is reused.
    count = (
        await db_session.execute(select(func.count()).select_from(User))
    ).scalar_one()
    assert count == 1


async def test_callback_race_on_email_falls_back_to_link_flow(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch, db_session: AsyncSession
):
    """A racer that holds the email but not the subject triggers the link flow."""
    await _make_user(db_session, email="race_email@example.com")

    _patch_github_calls(
        monkeypatch,
        token_payload={"access_token": "gho_race2"},
        profile={"id": 14141, "login": "raceemail"},
        emails=[
            {"email": "race_email@example.com", "primary": True, "verified": True}
        ],
    )

    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "race_code_2", "state": state},
        cookies=cookies,
    )
    assert resp.status_code == 200
    assert resp.json()["data"]["link_confirmation_required"] is True
    _assert_no_refresh_cookie(resp)
    _assert_state_cookie_cleared(resp)


async def test_callback_no_refresh_cookie_on_any_error_path(
    client: AsyncClient, monkeypatch: pytest.MonkeyPatch
):
    """Regression sweep: every error path leaves the refresh cookie unset."""
    from fastapi import HTTPException

    # Use a token-exchange failure as one representative error path; per-path
    # assertions are also made in the dedicated tests above.
    _patch_github_calls(
        monkeypatch,
        exchange_raises=HTTPException(502, "GitHub token exchange failed"),
    )
    state, cookies = _state_pair()
    resp = await client.get(
        f"{BASE}/github/callback",
        params={"code": "x", "state": state},
        cookies=cookies,
    )
    _assert_no_refresh_cookie(resp)


# ---------------------------------------------------------------------------
# Feature-flag-off — skipped per spec
# ---------------------------------------------------------------------------


@pytest.mark.skip(
    reason=(
        "Feature flag is checked at module import time; flipping it requires"
        " rebuilding the FastAPI app, which is more invasive than this slice"
        " allows. Documented as a Slice 5 omission."
    )
)
async def test_routes_404_when_feature_flag_off():
    pass
